server:
  port: 8080

com:
  csuyunlugu:
    wx:
      appid: wx0d53819c5a612d9f
      secret: a58388b63c9825333cce0512360a3d7f
    jwt:
      secret: lybugproducer
      expiration: 86400000
      exclude-urls:
        - /api/user/wxLogin
        - /api/admin/login
        - /uploads/**

user:
  default:
    username: 用户
    avatar: https://thirdwx.qlogo.cn/mmopen/vi_32/POgEwh4mIHO4nibH0KlMECNjjGxQUq24ZEaGT4poC6icRiccVGKSyXwibcPq4BWmiaIGuG1icwxaQX6grC9VemZoJ8rg/132

spring:
  datasource:
    username: root
    password: root